import = [ "~/.config/alacritty/aura.toml" ]

[font]
size = 9.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.8
# blur = true

[window.padding]
x = 15
y = 15

[shell]
program = "/bin/zsh"
args = ["-l"]

[selection]
save_to_clipboard = true

[mouse]
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]

