##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# ... parts of config
  workspace = 1, monitor:eDP-1, persistent:true
  workspace = 2, monitor:eDP-1, persistent:true
  workspace = 3, monitor:eDP-1, persistent:true
  workspace = 4, monitor:eDP-1, persistent:true
  workspace = 5, monitor:eDP-1, persistent:true
# ... another parts of config

